"""add receipt_pdf_path to payments

Revision ID: 370853351e60
Revises: 75dc4721ef02
Create Date: 2026-02-08 00:41:25.057687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370853351e60'
down_revision: Union[str, None] = '75dc4721ef02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_payments', sa.Column('receipt_pdf_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_payments', 'receipt_pdf_path')
    # ### end Alembic commands ###
