"""restore_tables_and_update_payments

Revision ID: 75dc4721ef02
Revises: 264384c2717b
Create Date: 2026-02-01 14:33:50.812587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75dc4721ef02'
down_revision: Union[str, None] = '264384c2717b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actioned_by_id', sa.UUID(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_approval_requests_id'), 'project_approval_requests', ['id'], unique=False)
    op.create_table('project_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('budget_type', sa.String(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budgets_id'), 'project_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_project_budgets_project_id'), 'project_budgets', ['project_id'], unique=False)
    op.add_column('project_payments', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('milestone_ids', sa.JSON(), nullable=True))
    op.add_column('project_payments', sa.Column('milestone_budget_sum', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('contract_work_order_no', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('client_type', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('client_department', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('payment_type', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('payment_category', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('project_payments', sa.Column('invoice_amount_gross', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('project_payments', sa.Column('converted_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('tax_type', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('tds_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('other_deductions_desc', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('net_receivable_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('retention_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('retention_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('balance_remaining', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('project_payments', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('account_holder_name', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('ifsc_swift_code', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('cheque_no', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('utr_transaction_ref', sa.String(), nullable=True))
    op.add_column('project_payments', sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_payments', 'attachments')
    op.drop_column('project_payments', 'utr_transaction_ref')
    op.drop_column('project_payments', 'cheque_no')
    op.drop_column('project_payments', 'ifsc_swift_code')
    op.drop_column('project_payments', 'account_number')
    op.drop_column('project_payments', 'account_holder_name')
    op.drop_column('project_payments', 'bank_name')
    op.drop_column('project_payments', 'balance_remaining')
    op.drop_column('project_payments', 'retention_percent')
    op.drop_column('project_payments', 'retention_amount')
    op.drop_column('project_payments', 'net_receivable_amount')
    op.drop_column('project_payments', 'other_deductions_desc')
    op.drop_column('project_payments', 'other_deductions')
    op.drop_column('project_payments', 'tds_percent')
    op.drop_column('project_payments', 'gst_percent')
    op.drop_column('project_payments', 'tax_type')
    op.drop_column('project_payments', 'converted_amount')
    op.drop_column('project_payments', 'exchange_rate')
    op.drop_column('project_payments', 'invoice_amount_gross')
    op.drop_column('project_payments', 'invoice_date')
    op.drop_column('project_payments', 'invoice_number')
    op.drop_column('project_payments', 'payment_category')
    op.drop_column('project_payments', 'payment_type')
    op.drop_column('project_payments', 'client_department')
    op.drop_column('project_payments', 'client_type')
    op.drop_column('project_payments', 'contract_work_order_no')
    op.drop_column('project_payments', 'milestone_budget_sum')
    op.drop_column('project_payments', 'milestone_ids')
    op.drop_column('project_payments', 'payment_id')
    op.drop_index(op.f('ix_project_budgets_project_id'), table_name='project_budgets')
    op.drop_index(op.f('ix_project_budgets_id'), table_name='project_budgets')
    op.drop_table('project_budgets')
    op.drop_index(op.f('ix_project_approval_requests_id'), table_name='project_approval_requests')
    op.drop_table('project_approval_requests')
    # ### end Alembic commands ###
