"""update tasks table

Revision ID: bc3e8a5da561
Revises: 370853351e60
Create Date: 2026-03-06 14:30:36.055424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc3e8a5da561'
down_revision: Union[str, None] = '370853351e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.alter_column('expenses', 'is_reversal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('expenses', 'is_fully_reversed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'project_payments', 'expenses', ['expense_id'], ['id'])
    op.add_column('tasks', sa.Column('task_code', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('module', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('assigned_by', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_hours', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('actual_hours', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('reviewers', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('watchers', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('notify_assignee', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('notify_watchers', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('notify_on_status_change', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_tasks_task_code'), 'tasks', ['task_code'], unique=True)
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_task_code'), table_name='tasks')
    op.drop_column('tasks', 'attachments')
    op.drop_column('tasks', 'notify_on_status_change')
    op.drop_column('tasks', 'notify_watchers')
    op.drop_column('tasks', 'notify_assignee')
    op.drop_column('tasks', 'watchers')
    op.drop_column('tasks', 'reviewers')
    op.drop_column('tasks', 'is_blocked')
    op.drop_column('tasks', 'progress')
    op.drop_column('tasks', 'actual_hours')
    op.drop_column('tasks', 'estimated_hours')
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'assigned_by')
    op.drop_column('tasks', 'module')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'task_code')
    op.drop_constraint(None, 'project_payments', type_='foreignkey')
    op.alter_column('expenses', 'is_fully_reversed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('expenses', 'is_reversal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notes_pkey'))
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    # ### end Alembic commands ###
