"""HR Leave Request — the main two-tier-approval table.

State machine: DRAFT → PENDING_MANAGER → PENDING_HR → APPROVED. Either pending
stage can reject (terminal). Employee can withdraw while PENDING_MANAGER.
Admins can override (POST /, lands APPROVED). On final approval the router
debits balance via `_apply_ledger` and re-runs `daily_rollup` for each affected
date so Attendance.status flips to LEAVE.

`reference_no` is a human-friendly identifier (format `LR-YY-NNNNNN`)
generated via an advisory-locked counter in `system_settings`. `fy_breakdown`
JSON column handles multi-day requests that cross 1 Apr: stored as
`{"2026-27": 3.0, "2027-28": 4.0}` so each FY's balance is debited correctly.

`day_breakdown` is computed on-read (see router) not stored.
"""
import uuid

from sqlalchemy import (
    Column, String, Boolean, DateTime, Date, ForeignKey,
    Enum, Integer, Text, Numeric, Index,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base
from app.models.hr.leave_type import LeaveType, LeaveStatus, LeaveSession, LeaveDecision


class LeaveRequest(Base):
    """Two-tier-approval leave request."""
    __tablename__ = "hr_leave_requests"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Human-friendly reference (LR-26-000023 etc.) — generated by router helper
    reference_no = Column(String(20), nullable=False, unique=True, index=True)

    employee_id = Column(UUID(as_uuid=True), ForeignKey("hr_employees.id", ondelete="CASCADE"), nullable=False, index=True)
    leave_type = Column(Enum(LeaveType, name="hr_leave_type"), nullable=False, index=True)

    from_date = Column(Date, nullable=False, index=True)
    to_date = Column(Date, nullable=False, index=True)
    total_days = Column(Numeric(4, 1), nullable=False, default=0)   # net days debited
    is_half_day = Column(Boolean, nullable=False, default=False)
    which_session = Column(Enum(LeaveSession, name="hr_leave_session"), nullable=True)

    # Cross-FY support: {"2026-27": 3.0, "2027-28": 4.0}
    fy_breakdown = Column(JSONB, nullable=False, default=dict)

    reason = Column(Text, nullable=False)
    attachment_id = Column(UUID(as_uuid=True), ForeignKey("drive_documents.id", ondelete="SET NULL"), nullable=True)
    contact_during_leave = Column(String(120), nullable=True)
    emergency_contact = Column(String(120), nullable=True)

    status = Column(Enum(LeaveStatus, name="hr_leave_status"), nullable=False, default=LeaveStatus.PENDING_MANAGER, index=True)

    # ──── Two-tier approval ────
    # Manager (employee.reporting_manager_id at submit time; cached for audit)
    manager_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True, index=True)
    manager_decision = Column(Enum(LeaveDecision, name="hr_leave_decision"), nullable=True)
    manager_decided_at = Column(DateTime(timezone=True), nullable=True)
    manager_notes = Column(Text, nullable=True)

    # HR / superadmin
    hr_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    hr_decision = Column(Enum(LeaveDecision, name="hr_leave_decision"), nullable=True)
    hr_decided_at = Column(DateTime(timezone=True), nullable=True)
    hr_notes = Column(Text, nullable=True)

    # Cancel / withdraw
    cancelled_at = Column(DateTime(timezone=True), nullable=True)
    cancelled_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    cancelled_reason = Column(Text, nullable=True)

    # Admin override (POST /) — lands APPROVED, skips both pending stages
    is_admin_override = Column(Boolean, nullable=False, default=False)

    # ──── Phase 4 — N-stage approval chain ────
    # Snapshot of the policy's approval_chain at submit time, augmented with
    # per-stage state. Each element:
    #   {
    #     "step": <0-based index>,
    #     "approver_type": "MANAGER" | "HR" | "USER",
    #     "approver_user_id": <uuid-str | null>,   # resolved at submit for MANAGER/USER
    #     "label": <str>,
    #     "decision": "APPROVED" | "REJECTED" | "SKIPPED" | null,
    #     "decided_by_id": <uuid-str | null>,
    #     "decided_at": <ISO-8601 | null>,
    #     "notes": <str | null>,
    #   }
    # Legacy in-flight requests (created pre-Phase 4) may have NULL/empty —
    # the router falls back to the manager_*/hr_* columns in that case.
    approval_steps = Column(JSONB, nullable=False, default=list)

    # 0-based pointer into approval_steps. Equals len(approval_steps) when
    # every stage has resolved (status moves to APPROVED).
    current_step = Column(Integer, nullable=False, default=0)

    # ──── Proof request (HR asks employee for supporting documents) ────
    # Set when HR hits POST /api/hr/leaves/{id}/request-proof. The employee
    # then uploads one or more LeaveProofAttachment rows via /me/{id}/proof.
    proof_requested = Column(Boolean, nullable=False, default=False, index=True)
    proof_requested_at = Column(DateTime(timezone=True), nullable=True)
    proof_requested_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    proof_request_note = Column(Text, nullable=True)
    # Stamped on the first successful proof upload — drives the HR "submitted"
    # indicator. Doesn't change on subsequent uploads.
    proof_submitted_at = Column(DateTime(timezone=True), nullable=True)

    is_deleted = Column(Boolean, nullable=False, default=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    employee = relationship("Employee", foreign_keys=[employee_id])

    # Non-deleted proof uploads — view-only relationship so callers can read
    # without touching the writeable LeaveProofAttachment session state.
    proof_attachments_rel = relationship(
        "LeaveProofAttachment",
        primaryjoin="and_(LeaveRequest.id==LeaveProofAttachment.leave_request_id, "
                    "LeaveProofAttachment.is_deleted==False)",
        viewonly=True,
    )

    __table_args__ = (
        Index("ix_hr_leave_emp_status", "employee_id", "status"),
        Index("ix_hr_leave_dates", "from_date", "to_date"),
        Index("ix_hr_leave_mgr_status", "manager_id", "status"),
        Index("ix_hr_leave_rollup", "employee_id", "status", "from_date", "to_date"),
    )
